---
output:
  html_document:
    md_extensions: +east_asian_line_breaks
    theme: null
    highlight: null
    css: style.css
params:
  group: NULL
  dose:  NULL
  toxic: NULL
  death: NULL
  total: NULL
pagetitle: 生物学的検定法
---

```{r, include=FALSE}
library(dplyr)
library(purrr)
library(tidyr)
library(modelr)
library(car)
library(ggplot2)
library(RColorBrewer)
library(gridExtra)
myfont <- "TeX Gyre Heros"

dat <- tibble(
    dose = params$dose,
    toxic = params$toxic,
    total = params$total
    ) %>%
    mutate(ldose = log10(dose),
           rate = toxic / total)

res <- tibble(dat = lst(dat)) %>%
    mutate(dat_s = map(dat,  ~ dplyr::filter(., rate > 0 & rate < 1)),
           glm = map(dat_s,
                     ~ glm(rate ~ ldose, weight = total,
                           family = binomial(probit), data = .)),
           logTD50 = map(glm,
                         ~ deltaMethod(., "-a/b",
                                       parameterNames= c("a", "b"))),
           TD50 = map(logTD50, ~ 10^.))

logTD50 <- res$logTD50[[1]]
TD50 <- res$TD50[[1]]


## fitted curve
pred <- tibble(ldose = seq_range(dat$ldose, n = 100, expand = 0.2)) %>%
    gather_predictions(res$glm[[1]], type = "response")



########################################
# Table
########################################
t1 <- dat %>%
    select(dose, total, toxic, rate) %>%
    mutate(rate = rate * 100) %>%
    tableGrob(cols = c("用量 (mg/kg)", "群の匹数",
                       "中毒の匹数", "反応割合 (%)"),
              theme = ttheme_default(base_size = 12),
              rows = NULL)

########################################
# plot
########################################
yval <- seq(0, 1, by = 0.1)

datg <- res$dat_s[[1]]

p <- ggplot(datg, aes(x = ldose, y = rate)) +
    geom_segment(x = -10, y = 0.5,
                 xend = logTD50$Estimate, yend = 0.5,
                 color = "gray") +
    geom_segment(x = logTD50$Estimate, y = 0.5,
                 xend = logTD50$Estimate, yend = -10,
                 color = "gray") +
    geom_line(data = pred, aes(y = pred)) +
    geom_point(size = 1.5) +
    scale_color_brewer(palette = "Set1")

p <- p +
    scale_x_continuous(breaks = dat$ldose, labels = dat$dose,
                       minor_breaks = NULL) +
    scale_y_continuous(breaks = yval, labels = yval * 100,
                       minor_breaks = NULL,
                       limits = c(0, 1)) +
    labs(x = "Dose (mg/kg)", y = "Response rate (%)") +
    annotate("text", x = logTD50$Estimate + 0.08, y = 0.03,
             label = sprintf("TD50 = %3.1f", TD50$Estimate),
             family = myfont) +
    theme_bw(base_family = myfont) +
    theme(legend.position = "none")
```


# 結果 (Group `r params$group`)
## 実験データ

```{r, echo=FALSE, fig.asp=0.4, out.width="70%", fig.align="center"}
grid.arrange(t1)
```

## あてはめ曲線

- 反応割合が0\%あるいは100\%のデータは使用せずに解析

```{r, echo=FALSE, fig.width=4, fig.asp=0.8, out.width="50%", fig.align="center"}
print(p)
```


## TD~50~値および95%信頼区間

- TD~50~ = `r sprintf("%3.1f", TD50[1])` mg/kg
（95%信頼区間 `r sprintf("%3.1f-%3.1f", TD50[3], TD50[4])`）

[（戻る）](index.html)
